server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET,POST,PUT,DELETE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/