server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=api/v1/users/**
#            - Method=GET,POST,PUT,DELETE
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/v1/books/admin/**

        - id: book-service
          uri: lb://book-service
          predicates:
             - Path=/api/v1/books/user/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/