server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: Welcome@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/