server:
  port: 8000
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: Welcome@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    deferDatasourceInitialization: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/