server:
  port: 8200
spring:
  application:
    name: readlist-service
  datasource:
    url: jdbc:mysql://localhost:3306/readlist
    username: root
    password: pass@word1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/